# Generated by Django 4.0.3 on 2022-04-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmerch_rename_address_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMerch',
            new_name='Moringa',
        ),
    ]
